(function(t,u){(function(){if(typeof require==="undefined"){var e=function(){},d={},h={};require=function(g){if(arguments.length>1){for(var c=require(arguments[0]),a=1;a<arguments.length;a++)require(arguments[a]);return c}g=g.split("@")[0];if(h[g]&&!d[g]){c=h[g];delete h[g];var b=d[g]=function(){return b.exports};b.browser=!0;b.exports={};c(b,b.exports)}return window[g]||(d[g]||e)()};require.define=function(d,c){h[d]=c}}})();require.define("json-sockets",function(e,d){var h=require("JSON"),g=require("common"),
c=require("curl"),a=function(){},b=function(){var b=function(a){this.host=a};b.prototype.type="ajax";b.prototype.get=function(a,b){this.destroy=c.get(this.host+a,b)};b.prototype.post=function(a,b,f){this.destroy=c.post(this.host+a,b,f)};b.prototype.destroy=a;if(c.cors)return b;b=function(a){this.host=a};b.prototype.type="jsonp";b.prototype.get=function(a,b){this.destroy=c.jsonp(this.host+a+(/\?/.test(a)?"&":"?")+"callback=?",b)};b.prototype.post=function(a,b,f){var i=0,d=this.host+a+(/\?/.test(a)?
"&":"?"),l=this,e=function(){var a=b.length<=(i+1)*1E3?f:g.fork(f,e),o=encodeURIComponent(b.substr(1E3*i++,1E3));l._destroy=c.jsonp(d+"post="+o+"&callback=?",a)};e()};b.prototype.destroy=a;return b}(),f=function(a){a="http://"+(a||window.location.host)+"/json-sockets";return new b(a)},p=function(){var a=g.encode((new Date).getTime()),b=0;return function(){return g.encode(b++)+a}}(),i=g.emitter(function(a){this.reader=f(a);this.writer=f(a);var b=this,c=this.reader,i=this.writer;this.type="longpoll-"+
c.type;this.destroyed=!1;this._ping=null;var d=function(){b.destroy()};c.get("/create?t="+p(),g.fork(d,function(a){var f=[],e=function(f){if(f)for(var f=f.split("\n"),i=0;i<f.length;i++)f[i]&&f[i]!=="pong"&&b.emit("message",h.parse(f[i]));b.destroyed||c.get("/read?id="+a+"&t="+p(),g.fork(d,e))},l=function(){if(f.length){var a=f.join("\n");f=[];q(a)}else b._send=q},r=function(a){f.push(a)},q=b._send=function(c){b._send=r;i.post("/write?id="+a+"&t="+p(),c+"\n",g.fork(d,l))};b._ping=setInterval(function(){b._send("ping")},
6E4);e();b.emit("open")}))});i.prototype.send=function(a){this._send(h.stringify(a))};i.prototype.destroy=function(){if(!this.destroyed)clearInterval(this._ping),this.destroyed=!0,this.reader.destroy(),this.writer.destroy(),this.emit("close")};i.prototype._send=function(){throw Error("socket is not writable");};var r=g.emitter(function(a){var b=this._ws=new WebSocket("ws://"+a+"/json-sockets"),c=this,f;b.onopen=function(){f=setInterval(function(){b.send("ping")},6E4);c.emit("open")};b.onmessage=function(a){a.data!==
"pong"&&c.emit("message",h.parse(a.data))};b.onclose=function(){clearInterval(f);c.emit("close")}});r.prototype.type="web-socket";r.prototype.send=function(a){this._ws.send(h.stringify(a))};r.prototype.destroy=function(){this._ws.close()};var q=window.WebSocket?r:i,m=function(a){document.body?a():(window.addEventListener||window.attachEvent)(window.attachEvent?"onload":"load",a,!1)},j=g.emitter(function(a){var b=this;this.type=q.prototype.type;this._buffer=[];m(function(){if(!b._destroyed){var c=
b._sock=new q(a),f=!1,i=function(){c.destroy()};b.destroy=function(){f=!0};c.on("open",function(){if(f)i();else{for(;b._buffer.length;)b._send(b._buffer.shift());b.send=b._send;b.destroy=i;b.emit("open")}});c.on("message",function(a){b.emit("message",a)});c.on("close",function(){b.emit("close")})}})});j.prototype.send=function(a){this._buffer.push(a)};j.prototype.destroy=function(){this._destroyed=!0;this.emit("close")};j.prototype._send=function(a){this._sock.send(a)};d.connect=function(a){a=a||
window.location.host;return new j(a)}});require.define("common",function(e,d){var h=function(){},g;e.browser?(g=function(){this._events={}},g.prototype.on=g.prototype.addListener=function(c,a){this.emit("newListener",c,a);(this._events[c]=this._events[c]||[]).push(a)},g.prototype.once=function(c,a){var b=this,f=function(){b.removeListener(c,a);a.apply(this,arguments)};f.listener=a;this.on(c,f)},g.prototype.emit=function(c){var a=this._events[c];if(a)for(var b=Array.prototype.slice.call(arguments,
1),a=a.slice(),f=0;f<a.length;f++)a[f].apply(null,b)},g.prototype.removeListener=function(c,a){var b=this._events[c];if(b){for(var f=0;f<b.length;f++)if(b[f]===a||b[f].listener===a){b.splice(f,1);break}b.length||delete this._events[c]}},g.prototype.removeAllListeners=function(c){arguments.length?delete this._events[c]:this._events={}},g.prototype.listeners=function(c){return this._events[c]||[]}):g=require("events").EventEmitter;Object.create=Object.create||function(c){var a=function(){};a.prototype=
c;return new a};d.extend=function(c,a){var b=function(){c.call(this);a.apply(this,arguments)};b.prototype=Object.create(c.prototype);return b};d.createEmitter=function(){return new g};d.emitter=function(c){return d.extend(g,c)};d.fork=function(c,a){return function(b,f){b?c(b):a(f)}};d.step=function(c,a){var b=0,f=0,d=0,i=!1,g={},e=null,m=!1,j=function(l,o){if(l&&!i)i=!0,(a||h).apply(g,[l]);else if(!(i||b&&!(m&&f>=b))){var n=c[d++],k=n.length===1?[j]:[o,j];b=f=0;e=[];m=!1;n.apply(g,d<c.length?k:[o,
j]);m=!0;b&&m&&f>=b&&j(null,e)}};j.parallel=function(){var a=b++;if(m)throw Error("next.parallel must not be called async");return function(b,c){f++;e[a]=c;j(b,e)}};j()};d.memoizer=function(c){var a={},b=function(a){var c=typeof a;if(c!=="object")return c+": "+a;var c=[],i;for(i in a)c.push(b(a[i]));return c.sort().join("\n")};return function(){for(var f="",d=0;d<arguments.length;d++)f+=b(arguments[d])+"\n";a[f]=a[f]||c.apply(null,arguments);return a[f]}};d.curry=function(c){var a=Array.prototype.slice.call(arguments,
1);return function(){return c.apply(this,a.concat(Array.prototype.slice.call(arguments)))}};d.once=function(c){var a=!0;return function(){if(a)return a=!1,(c||h).apply(null,arguments),!0;return!1}};d.future=function(){var c={},a=[];c.get=function(b){a.push(b)};c.put=function(b,f){for(c.get=function(a){a(b,f)};a.length;)a.shift()(b,f)};return c};d.encode=function(){return function(c){return c<62?"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(c):d.encode(Math.floor(c/62))+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(c%
62)}}();d.uuid=function(){var c=0;return function(){for(var a="",b=0;b<36;b++)a+=d.encode(Math.floor(Math.random()*62));return a+"-"+d.encode(c++)}}();d.gensym=function(){var c=0;return function(){return"s"+c++}}();d.format=function(c,a){a=typeof a==="object"?a:Array.prototype.slice.call(arguments,1);return c.replace(/\{([^{}]+)\}/gm,function(b,c){return a[c]===void 0?b:a[c]})};d.log=function(){var c=d.format.apply(d,arguments);(typeof window==="undefined"||window.console)&&console.log(c)}});require.define("JSON",
function(){typeof JSON==="undefined"&&(JSON={});(function(){function e(a){return a<10?"0"+a:a}function d(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var b=f[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function h(c,f){var e,g,j,l,o=a,n,k=f[c];k&&typeof k==="object"&&typeof k.toJSON==="function"&&(k=k.toJSON(c));typeof p==="function"&&(k=p.call(f,c,k));switch(typeof k){case "string":return d(k);case "number":return isFinite(k)?
String(k):"null";case "boolean":case "null":return String(k);case "object":if(!k)return"null";a+=b;n=[];if(Object.prototype.toString.apply(k)==="[object Array]"){l=k.length;for(e=0;e<l;e+=1)n[e]=h(e,k)||"null";j=n.length===0?"[]":a?"[\n"+a+n.join(",\n"+a)+"\n"+o+"]":"["+n.join(",")+"]";a=o;return j}if(p&&typeof p==="object"){l=p.length;for(e=0;e<l;e+=1)typeof p[e]==="string"&&(g=p[e],(j=h(g,k))&&n.push(d(g)+(a?": ":":")+j))}else for(g in k)Object.prototype.hasOwnProperty.call(k,g)&&(j=h(g,k))&&n.push(d(g)+
(a?": ":":")+j);j=n.length===0?"{}":a?"{\n"+a+n.join(",\n"+a)+"\n"+o+"}":"{"+n.join(",")+"}";a=o;return j}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+e(this.getUTCMonth()+1)+"-"+e(this.getUTCDate())+"T"+e(this.getUTCHours())+":"+e(this.getUTCMinutes())+":"+e(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a,b,f={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},p;if(typeof JSON.stringify!=="function")JSON.stringify=function(c,f,d){var e;b=a="";if(typeof d==="number")for(e=0;e<d;e+=1)b+=" ";else typeof d==="string"&&(b=d);if((p=f)&&typeof f!=="function"&&(typeof f!=="object"||typeof f.length!=="number"))throw Error("JSON.stringify");return h("",
{"":c})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,f){var d,e,g=a[f];if(g&&typeof g==="object")for(d in g)Object.prototype.hasOwnProperty.call(g,d)&&(e=c(g,d),e!==void 0?g[d]=e:delete g[d]);return b.call(a,f,g)}var f,a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),typeof b==="function"?c({"":f},""):f;throw new SyntaxError("JSON.parse");}})()});require.define("curl",function(e,d){typeof XMLHttpRequest=="undefined"&&(XMLHttpRequest=function(){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}throw Error("This browser does not support XMLHttpRequest.");});var h=function(){},
g=[],c=function(a,b,c,d){var e=g.length?g.pop():new XMLHttpRequest,r=function(){g.push(e);d(!/2\d\d/.test(e.status)&&Error("invalid status="+e.status),e.responseText)};e.open(a,b,!0);e.onreadystatechange=function(){if(e.readyState===4)e.onreadystatechange=h,setTimeout(r,1)};e.send(c);return function(){e.onreadystatechange=h;e.abort();d(Error("request aborted"))}};d.cors="withCredentials"in new XMLHttpRequest;d.get=function(a,b){return c("GET",a,null,b)};d.post=function(a,b,f){typeof b==="function"&&
(f=b,b=null);return c("POST",a,b,f||h)};d.jsonp=function(){var a=window._tmp_jsonp={},b="cb"+(new Date).getTime(),c=0,e=function(a,b){window.attachEvent?window.attachEvent("on"+a,b):window.addEventListener(a,b,!1)};return function(d,g,q){typeof g==="function"&&(q=g,g={});var g=g||{},q=q||h,m=b+c++,j=!1,l=function(b,c){j=!0;var d=document.getElementById(m);if(d)d.onreadystatechange=h,d.parentNode.removeChild(d);delete a[m];q(b,c)};a[m]=function(a){if(g.strict&&(a===void 0||a===null||a.error)){var b=
Error(a&&a.error||"result is undefined or null");if(a)for(var c in a)b[c]=a[c];l(b)}else l(null,a)};var d=d.replace(/(\?|\&)(callback|jsonp)=\?/,"$1$2=_tmp_jsonp."+m),o=function(){if(!j){var a=document.createElement("script");a.async=!0;a.src=d;a.id=m;document.body.appendChild(a)}};document.body||g.async?document.body?o():e("load",o):document.write(unescape("%3Cscript")+' src="'+d+'" id="'+m+'"'+unescape("%3E%3C/script%3E"));document.getElementById(m).onreadystatechange=function(){j||this.readyState!==
"loaded"&&this.readyState!=="complete"||l(Error("jsonp request failed"))};return function(){l(Error("jsonp request was cancelled"))}}}()});var v=require("json-sockets"),w=require("common"),x=function(){},y=function(e){if(e&&typeof e==="object")return e;e=((e||"").match(/([^:\/]*)(?::(\d+))?(?:\/(.*))?/)||[]).slice(1);return{host:e[0]||"localhost",port:parseInt(e[1]||(t.browser?80:10547),10),sub:e[2]||"/"}},s=function(e){for(var d in e)Object.prototype.toString.call(e[d])==="[object RegExp]"?e[d]=
{$regex:""+e[d]}:typeof e==="object"&&(e[d]=s(e[d]));return e};u.connect=function(e){var e=y(e),d=v.connect(e.host+":"+e.port),h={},g={};d.send({sub:e.sub});d.on("message",function(c){c.name==="publish"&&(g[c.id]||x)(c.doc)});h.subscribe=function(c,a,b){b||(b=a,a=void 0);var e=w.gensym();g[e]=b;d.send({name:"subscribe",id:e,query:s(c),selection:a});return function(){delete g[e];d.send({name:"unsubscribe",id:e})}};h.publish=function(c,a){d.send({name:"publish",doc:c,challenge:a})};return h}})({browser:!0},
window.pubsubio={});